spring:
  datasource:
    url: "jdbc:h2:~/test3"
    driver-class-name: org.h2.Driver
    #username: '{cipher}aef003ba1152d30e645b10d697da5369aa5b345e749779ecc14b0686b91393ab' #대칭키 암호
    username: '{cipher}AQBBeOAxx7i3WH16kN5DAWEu81lG954hF19M24jqa3T7OQpS84KgOlXY0AXV/MIeYLxA34BFF8RgGDgOm3Rdi8cWz105g+9NKGTPUVVIs/AjqpAZ2eIsm5m9DwiD2IfXWZxIFDXkFs7kWoe+oxbHzyC7hz8eJ20d362L6YVFeQT/cRTxElgnMZTbfTV/zqWs5BauTNBUzbB4u3vIP3CO7NGVrTFJknQZs4xgyTPDh0DenBn0qn5aQrIe2t+l4Ixam8RzqaXpnLCqE857z0Ft0B83/yLxGSszxDZ/xT2HPb79ESU/BFuJzSp7Dr7LzU3EA3G5PSrSP4TUOV2m7Oy7eKyJfJojocujfg3QohFMxo7D7r9DUud7Y8FZ/qL4LpWex0Y='   #비대칭키 암호
  jwt:
    token:
      header: Authorization
      type: Bearer
      secret-key: '{cipher}AQArW2p8aTKyMbXjmu6XBLuvqrq7yBpCOV7xMigE0cBsxqTEpPGH/eT9/FLZA/R0wvB9Nd27nuw1CnK/cSbwEFAcHchCy4ez3gThj0VM5em7XcCg3cuW27g/DOhWET8mZ8Qo6TWJbc9KuRZHSUcXBZNbuYWdIewQhIPf9ig92D3T+V683HNYoHaG8O3TkD5zfIZE2Bym1EregzU9HPv4Bp9R047/dbADLGsEI6aItnveHCjYN6ZU0NbNQBuOrw3HZ6aj4JmjcA0Mkt/AtWv/u4INkjftm2EebhQnsDkYeCj+Lg0cD3RvqYWbc5Qzle3VENqOYRAaoA2UZGFYy+RYHqbzyrWNFWwZmHNB8YGv4IMvri2rDnEykUK7cHdux1VvVwyhoMeZzalqM2sLonXbvXiqilQTMxXknYhH7kctB9+T46qW7b+2IhmmfYrcoKmj2/c1POuffL/3SDgyBgTiZtZ+KUFmzvKZwtRO9mT+gd2dexVFXtdRk4eqTS/OV194VRI7TL8ZbvsvVyhMUhJAPuYI'
      expire-length: 864000000 # 10days