spring:
  datasource:
    url: "jdbc:h2:~/test3"
    driver-class-name: org.h2.Driver
    #username: '{cipher}aef003ba1152d30e645b10d697da5369aa5b345e749779ecc14b0686b91393ab' #대칭키 암호
    username: '{cipher}AQAjxj/PnvsQ9xDp2Lx8h2oeOEmXaQtg6yhat8I8h7TjN0r2FvI3f/WyRWRqyIND0xTBnvY4cuBjvgExe+vwDV9Kq03kwJPCRFBnjP3HugJJF5CwpKMJRK+kDMHm2atSWLqydX5Q6lxtTscYPWwjc2vZdKm0cUL4dSztJswW+wSjuAt1fICdIkJg0ZEyLc3vI9F1RjzcCb+3comkfE0PejW0Eyx4tg4S9c1EfRLOAnZmc0W1K0hFhzHHj0IqvXxzXCeLUPm2SQzRXazb2yomNC71NXOUFgdbCJwEEeX1hHrht5ZT9/MF2M8wFAJK0YqGHKt5/QvzbjmJD94fEOrgVZnwPsaYWzAeqnW8nowFnI0zU4xrW0CC//Sh0ZdqyWRpNkI='   #비대칭키 암호
  jwt:
    token:
      header: Authorization
      type: Bearer
      secret-key: '{cipher}AQArW2p8aTKyMbXjmu6XBLuvqrq7yBpCOV7xMigE0cBsxqTEpPGH/eT9/FLZA/R0wvB9Nd27nuw1CnK/cSbwEFAcHchCy4ez3gThj0VM5em7XcCg3cuW27g/DOhWET8mZ8Qo6TWJbc9KuRZHSUcXBZNbuYWdIewQhIPf9ig92D3T+V683HNYoHaG8O3TkD5zfIZE2Bym1EregzU9HPv4Bp9R047/dbADLGsEI6aItnveHCjYN6ZU0NbNQBuOrw3HZ6aj4JmjcA0Mkt/AtWv/u4INkjftm2EebhQnsDkYeCj+Lg0cD3RvqYWbc5Qzle3VENqOYRAaoA2UZGFYy+RYHqbzyrWNFWwZmHNB8YGv4IMvri2rDnEykUK7cHdux1VvVwyhoMeZzalqM2sLonXbvXiqilQTMxXknYhH7kctB9+T46qW7b+2IhmmfYrcoKmj2/c1POuffL/3SDgyBgTiZtZ+KUFmzvKZwtRO9mT+gd2dexVFXtdRk4eqTS/OV194VRI7TL8ZbvsvVyhMUhJAPuYI'
      expire-length: 864000000 # 10days
