spring:
  datasource:
    url: "jdbc:h2:~/test3"
    driver-class-name: org.h2.Driver
    #username: '{cipher}aef003ba1152d30e645b10d697da5369aa5b345e749779ecc14b0686b91393ab' #대칭키 암호
    username: '{cipher}AQBBeOAxx7i3WH16kN5DAWEu81lG954hF19M24jqa3T7OQpS84KgOlXY0AXV/MIeYLxA34BFF8RgGDgOm3Rdi8cWz105g+9NKGTPUVVIs/AjqpAZ2eIsm5m9DwiD2IfXWZxIFDXkFs7kWoe+oxbHzyC7hz8eJ20d362L6YVFeQT/cRTxElgnMZTbfTV/zqWs5BauTNBUzbB4u3vIP3CO7NGVrTFJknQZs4xgyTPDh0DenBn0qn5aQrIe2t+l4Ixam8RzqaXpnLCqE857z0Ft0B83/yLxGSszxDZ/xT2HPb79ESU/BFuJzSp7Dr7LzU3EA3G5PSrSP4TUOV2m7Oy7eKyJfJojocujfg3QohFMxo7D7r9DUud7Y8FZ/qL4LpWex0Y='   #비대칭키 암호
  jwt:
    token:
      header: Authorization
      type: Bearer
      secret-key: '{cipher}AQCTCQo4fU4zrpuVc47SBQytT+Oe52QOVr3xkgJwuwtzv+WEsfkICfDk0GQNIYv28JQGNz3SRK2BL/elxJl4BFYXmUySov0pGRPqZudWnXqut6GU4rYiNgVZVrLL27xC0Mnm7uVrn8snkrjsDvRGUxf+qEbaDRw907NHp2Zn3XKsK6m9FrEzXWJlO3ByeNeV0aJoER5hxXwSK/3d/trTaNYH0pMHABmX09I7eDRQxJE2MTlkk3OLH8LZ5/awniAlxrVZqLWK3wzAZV1Fp04tXoO6MZpc6+7+SOYfTTtjuflVL/5dvks0p5TetLhtlIUBtc0J73J//BPyvj0Uro3yiCLI/8kQQU0WpjDZNEPvZKqTrwC8NrDS+rlJuc7sEDm5MbUa693A1RBfxLIQf6BwtKy13tENzYL6F2+DMN9CgZJH22v6vHiEkxjxfg/FO6zxWZsOyzpj24W4/5Ds+bGnRvrMcm8q1dbBiGq0BrnKMUeRV4vwd3vx+FB9Hbm4A7Mq4wa9dcSH95LqC8NmjBYmAdCo'
      expire-length: 864000000 # 10days