spring:
  datasource:
    url: "jdbc:h2:~/test3"
    driver-class-name: org.h2.Driver
    #username: '{cipher}aef003ba1152d30e645b10d697da5369aa5b345e749779ecc14b0686b91393ab' #대칭키 암호
    username: '{cipher}AQBBeOAxx7i3WH16kN5DAWEu81lG954hF19M24jqa3T7OQpS84KgOlXY0AXV/MIeYLxA34BFF8RgGDgOm3Rdi8cWz105g+9NKGTPUVVIs/AjqpAZ2eIsm5m9DwiD2IfXWZxIFDXkFs7kWoe+oxbHzyC7hz8eJ20d362L6YVFeQT/cRTxElgnMZTbfTV/zqWs5BauTNBUzbB4u3vIP3CO7NGVrTFJknQZs4xgyTPDh0DenBn0qn5aQrIe2t+l4Ixam8RzqaXpnLCqE857z0Ft0B83/yLxGSszxDZ/xT2HPb79ESU/BFuJzSp7Dr7LzU3EA3G5PSrSP4TUOV2m7Oy7eKyJfJojocujfg3QohFMxo7D7r9DUud7Y8FZ/qL4LpWex0Y='   #비대칭키 암호
  jwt:
    token:
      header: Authorization
      type: Bearer
      secret-key: '{cipher}AQBlX4cxcQ+PG+VMRvgwbkp0NlWiK2/HfD8NJbxQV4MxDcTkSs89G061439GabE3u4dgbK79DYfev8tAyK1s9wc0yXRtfz4VIvRBzKEzaj4TF+Sy9/Bsls8DnOXI/HDlAmyObIDDSCSa8x1K8vdeW4yY+jstrcrUqaCX8kPfyKlL4b0AB0jCymgapjAh0EBbEoac9l+QJ+6WaQURGlW/hgARI9CXbVOtYLPigt+JpsekxtLVC/9cUstLlIBtbd0LUmbhcHuJ1JYdWPeQxSaHTgfVoI0VkuxCWnVYOsYG5SJMNogvVYfEQ92BoYt1q2a5c052iIcBgDZbohzRxIZt1y3zuJgcyrqtAyccZKBm5tLn4/tSUWPJRKA2I7msUKsxeUhJ23MDG7DibJvV5lmdYPzM'
      expire-length: 864000000 # 10days